spring.application.name=TheRaven_TestTask

spring.datasource.url=jdbc:postgresql://localhost:5432/TheRaven
spring.datasource.username=postgres
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true